id: I27B1C66E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T23:00:58+00:00'
last_modified: '2022-06-07T22:09:33.379024+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG03652
  title: ཆོས་ཀྱི་སྣང་བ་གསར་པ
  author: ''
  base:
    B5B4:
      image_group_id: I00KG03731
      title: ''
      total_pages: 210
      order: 1
      base_file: B5B4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
